#!/bin/bash
# Wrapper script for firewall.sh with simplified commands

# on/off: Enable/disable host network access (web browsing)
# enable/disable: Enable/disable entire firewall (change default policy)
# flush: Flush all iptables chains
# start: Load firewall rules

if [[ "$1" == "on" ]]; then
	ACTION="enable-net"
elif [[ "$1" == "off" ]]; then
	ACTION="disable-net"
elif [[ "$1" == "disable" ]]; then
	ACTION="$1"
elif [[ "$1" == "enable" ]]; then
	ACTION="$1"
elif [[ "$1" == "flush" ]]; then
	ACTION="$1"
elif [[ "$1" == "start" ]]; then
	ACTION="$1"
else
	echo "Usage: $0 [on|off|disable|enable|flush|start]" 1>&2;
	echo "" 1>&2;
	echo "Commands:" 1>&2;
	echo "  on       - Enable host network access" 1>&2;
	echo "  off      - Disable host network access" 1>&2;
	echo "  enable   - Enable firewall (default DROP policy)" 1>&2;
	echo "  disable  - Disable firewall (default ACCEPT policy)" 1>&2;
	echo "  flush    - Flush all iptables rules" 1>&2;
	echo "  start    - Load/restart firewall rules" 1>&2;
	exit 1
fi

sudo /etc/firewall.sh ${ACTION} 'silent'
